import os
import json
import litellm
from datetime import datetime

# Defaulting to Gemini 2.0 Flash via LiteLLM for all agents for simplicity,
# but can be overridden by environment variables to use different models.
RISK_MODEL = os.getenv("RISK_MODEL", "gemini/gemini-2.0-flash")
TECH_MODEL = os.getenv("TECH_MODEL", "gemini/gemini-2.0-flash")
MACRO_MODEL = os.getenv("MACRO_MODEL", "gemini/gemini-2.0-flash")
PM_MODEL = os.getenv("PM_MODEL", "gemini/gemini-2.0-flash")

def load_text_file(filepath):
    if os.path.exists(filepath):
        with open(filepath, 'r') as f:
            return f.read()
    return ""

def build_context():
    # Load Market Data
    market_data_str = load_text_file('data/market_context.json')
    
    # Load Thesis
    macro_view = load_text_file('thesis/macro_view.md')
    sectors = load_text_file('thesis/sectors.md')
    seasonality = load_text_file('thesis/seasonality_rules.md')
    
    # Load Portfolio & Watchlist
    portfolio = load_text_file('portfolio.csv')
    watchlist = load_text_file('watchlist.csv')
    
    context = f"""
# MARKET DATA (JSON)
{market_data_str}

# CURRENT PORTFOLIO
{portfolio}

# WATCHLIST
{watchlist}

# INVESTMENT THESIS
## Macro View
{macro_view}

## Sectors
{sectors}

## Seasonality Rules
{seasonality}
"""
    return context

def run_agent(role, prompt, model, context):
    print(f"Running {role} agent with model {model}...")
    try:
        response = litellm.completion(
            model=model,
            messages=[
                {"role": "system", "content": f"You are an expert {role} in a quantitative hedge fund."},
                {"role": "user", "content": f"Here is the context:\n{context}\n\nTask: {prompt}"}
            ]
        )
        return response.choices[0].message.content
    except Exception as e:
        print(f"Error running {role} with {model}: {e}")
        if "gemini-1.5" in model:
            print(f"Falling back to gemini/gemini-1.5-flash for {role}...")
            try:
                fallback_model = "gemini/gemini-1.5-flash"
                response = litellm.completion(
                    model=fallback_model,
                    messages=[
                        {"role": "system", "content": f"You are an expert {role} in a quantitative hedge fund."},
                        {"role": "user", "content": f"Here is the context:\n{context}\n\nTask: {prompt}"}
                    ]
                )
                return response.choices[0].message.content
            except Exception as e2:
                print(f"Error running fallback {role}: {e2}")
                return f"Error: {e2}"
        return f"Error: {e}"

def generate_reports():
    context = build_context()
    date_str = datetime.now().strftime("%Y-%m-%d")
    
    # 1. Risk Manager
    risk_prompt = "Focus entirely on downside protection. Analyze the market regime, volatility (VIX), and highlight any bearish divergence or macro risks from the news. What should we sell or hedge?"
    risk_report = run_agent("Risk Manager", risk_prompt, RISK_MODEL, context)
    
    # 2. Technical Analyst
    tech_prompt = "Ignore the news. Evaluate the setups purely based on price action, moving averages (SMA_20, SMA_50, SMA_200), RSI, and MACD. Identify mean reversion bounces or volatility contraction squeezes."
    tech_report = run_agent("Technical Analyst", tech_prompt, TECH_MODEL, context)
    
    # 3. Macro Strategist
    macro_prompt = "Focus on the macro view, seasonality rules, and global equity/commodity trends. How does the current date and news align with our seasonality rules? Are there any sector rotations evident?"
    macro_report = run_agent("Macro Strategist", macro_prompt, MACRO_MODEL, context)
    
    # 4. Portfolio Manager (Synthesizer)
    pm_prompt = f"""
You are the Lead Portfolio Manager. Review the reports from your analysts below. 
Note: The source model used to generate each report is provided. When debating disagreements, you should generally heavily weight opinions from advanced/paid frontier models (e.g., GPT-4, Claude 3.5 Sonnet) over faster/free-tier models (e.g., Gemini Flash, Llama 3 8B), while still considering the merit of the underlying argument.

## Risk Manager Report (Generated by: {RISK_MODEL})
{risk_report}

## Technical Analyst Report (Generated by: {TECH_MODEL})
{tech_report}

## Macro Strategist Report (Generated by: {MACRO_MODEL})
{macro_report}

Weigh these inputs against our investment thesis and portfolio constraints.
Debate disagreements. Output a definitive, actionable plan.

FIRST, provide your analysis and a strict Markdown table containing:
| Action (Buy/Sell/Hold) | Ticker/Asset | Conviction Level (High/Medium/Low) | Timeframe | Justification |

SECOND, at the very end of your response, output a strict, parseable JSON array of the trades you want to execute. Do not include 'Hold' actions in the JSON. For fractionable shares, use dollar amounts instead of shares. Wrap the JSON in a markdown code block like ```json ... ```.

The JSON format MUST be exactly this structure:
[
  {{
    "ticker": "MSFT",
    "action": "buy",
    "notional_value": 200000
  }},
  {{
    "ticker": "AAPL",
    "action": "sell",
    "qty": "all"
  }}
]
"""
    pm_report = run_agent("Portfolio Manager", pm_prompt, PM_MODEL, context)
    
    # Extract JSON trades
    trades = []
    display_report = pm_report
    try:
        # Simple extraction looking for ```json ... ```
        if "```json" in pm_report:
            json_str = pm_report.split("```json")[1].split("```")[0].strip()
            trades = json.loads(json_str)
            # Remove the JSON block from the display report so the website looks clean
            display_report = pm_report.split("```json")[0].strip()
    except Exception as e:
        print(f"Failed to extract JSON trades from PM report: {e}")

    with open('data/trades.json', 'w') as f:
        json.dump(trades, f, indent=4)
        print("Trades saved to data/trades.json")

    
    # Save reports
    os.makedirs('docs', exist_ok=True)
    os.makedirs('docs/reports', exist_ok=True)
    
    with open('docs/reports/risk.md', 'w') as f:
        f.write(f"# Risk Manager Report - {date_str}\n\n{risk_report}")
        
    with open('docs/reports/tech.md', 'w') as f:
        f.write(f"# Technical Analyst Report - {date_str}\n\n{tech_report}")
        
    with open('docs/reports/macro.md', 'w') as f:
        f.write(f"# Macro Strategist Report - {date_str}\n\n{macro_report}")
        
    with open('docs/index.md', 'w') as f:
        f.write(f"# AlphaOracle Daily Synthesis - {date_str}\n\n{display_report}")
        
    print("Reports generated successfully.")

if __name__ == "__main__":
    generate_reports()
